version: "3.7"
services:
  app:
    build: app
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kohana
    volumes:
      - ./app/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

#  exploit:
#    build: exploit
#    depends_on:
#      - app

volumes:
  dbdata:
